/*! \file 0_EcoSystemVersions.h
	\brief
*/

#ifndef __ECOSYSTEM_VERSIONS__
#define __ECOSYSTEM_VERSIONS__

#define ECOSYSTEM_MAJORVERSION 0
#define ECOSYSTEM_MINORVERSION 1
#define ECOSYSTEM_BUILDNUMBER 0

#define ECOSYSTEM_DEVSPECIFIER dev
#define ECOSYSTEM_VERSIONDATE 08JAN2021

#ifdef ECOSYSTEM_RELEASEBUILD
#define ECOSYSTEM_VERSIONNUMBER ECOSYSTEM_MAJORVERSION.ECOSYSTEM_MINORVERSION.ECOSYSTEM_BUILDNUMBER
#endif
#ifndef ECOSYSTEM_RELEASEBUILD
#define ECOSYSTEM_VERSIONNUMBER ECOSYSTEM_MAJORVERSION.ECOSYSTEM_MINORVERSION.ECOSYSTEM_BUILDNUMBER-ECOSYSTEM_DEVSPECIFIER
#endif

#define ECOSYSTEM_VERSIONSTRING str(ECOSYSTEM_VERSIONNUMBER)
#define ECOSYSTEM_VERSIONDATESTRING str(ECOSYSTEM_VERSIONDATE)

#endif /// !__ECOSYSTEM_VERSIONS__
