#include "3_Packet_HDRPACK.h"
using namespace IMSPacketsAPICore;

TEMPLATE_STATICPACKETINFO_CPP(HDRPACK)

TEMPLATE_SPDACCESSORS_CPP(pCLASS(HDRPACK), PacketType, iHDRPACK_PacketType, typeINT, "%d")
TEMPLATE_SPDACCESSORS_CPP(pCLASS(HDRPACK), PacketOption, iHDRPACK_PacketOption, typeINT, "%d")